name: drudge
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:

# custom <drudge dependencies>

  id: "^1.0.13"
  ebisu: ">0.6.14 <0.8.0"
  glob: "^1.1.0"  

# end <drudge dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <drudge dev dependencies>
  test: "^0.12.0"

# end <drudge dev dependencies>

dependency_overrides:
# custom <drudge dependency overrides>
# end <drudge dependency overrides>

transformers:

# custom <drudge transformers>
# end <drudge transformers>

